version: '3.8'

services:
  app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Minhajsiddiqui@1997
      - MYSQL_DATABASE=digitaltwin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./heart datasets:/app/heart datasets

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Minhajsiddiqui@1997
      - MYSQL_DATABASE=digitaltwin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./digital_twin_patient.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: 